#!/usr/bin/python3
#
# See https://github.com/svn-all-fast-export/svn2git/issues/146#issuecomment-1183011430
#
import sys
import re
import os
import csv
import traceback
from collections import OrderedDict

def loadLogs():
    svn2marks = 'svn2marks.csv'
    marks_ttssh2 = 'ttssh2/marks-ttssh2'

    svnMap = OrderedDict()
    if os.path.exists(svn2marks):
        with open(svn2marks, "r", newline='') as f:
            reader = csv.DictReader(f)
            for row in reader:
                mark = row['mark']
                rev = int(row['revnum'])
                if rev not in svnMap:
                    svnMap[rev] = []
                svnMap[rev].append(mark)

    # sample of 'marks-ttssh2'
    # :1 e62e564072f23a29c39c1ff539849bceab61785b
    gitMap = OrderedDict()
    if os.path.exists(marks_ttssh2):
        with open(marks_ttssh2, "r") as f:
            for line in f:
                data =  line.split()
                mark = data[0].replace(':', '')
                commitHash = data[1]
                gitMap[mark] = commitHash

    return svnMap, gitMap

def showHashes(svn_revs):
    try:
        svnMap, gitMap = loadLogs()
        for rev in svn_revs:
            if rev in svnMap:
                for mark in svnMap[rev]:
                    if mark in gitMap:
                        commitHash = gitMap[mark]
                        print(f"* r{rev}: {commitHash} https://osdn.net/projects/ttssh2/scm/svn/commits/{rev}")
                    else:
                        print(f"* r{rev}: NotFound mark={mark} https://osdn.net/projects/ttssh2/scm/svn/commits/{rev}")
                        gitList = list(gitMap.items())
                        print("rev:", rev, "mark", mark)
                        print(gitList[-1])
            else:
                print(f"* r{rev}: NotFound https://osdn.net/projects/ttssh2/scm/svn/commits/{rev}")
                gitList = list(gitMap.items())
                print("rev:", rev)
                print(gitList[-1])
    except Exception as e:
        a, b, c = sys.exc_info()
        traceback.print_tb(c)
        for rev in svn_revs:
            print(f"* r{rev}: NotFound https://osdn.net/projects/ttssh2/scm/svn/commits/{rev}")

repoDir = "ttssh2"

allRevs = set()
allIssues = set()

revLogMatched = set()
issueLogMatched = set()
issueLogUnmatched = set()

for line in sys.stdin:
    line = line.rstrip("\r").rstrip("\n")
    print(line)

    # ignore message by cvs2svn
    r = re.search('This commit was generated by cvs2svn to compensate for changes', line)
    if r:
        #sys.stderr.write(f"ignore: {line}\n")
        continue

    # NG: -rXXX
    # NG: rXXX-
    # OK: rXXX-rYYY
    # OK: rXXX - rYYY
    # OK: (rXXX)
    # NG: rXXX_
    # OK: rXXX,
    # OK:  rXXX (space before and/or after revision)

    revRange = r"r(\d+)\s*-\s*r(\d+)"
    revOne   = r"r(\d+)"
    endMark  = r"((?=[^0-9-&/=@_])|$)"
    pattern  = "(" + revRange + ")" + "|" + r"(\b" + revOne + endMark  + ")"

    r = re.finditer(pattern, line)
    for m in r:
        matched = m.group(0)
        revs = re.split(r'\s*-\s*', matched)
        for rev in revs:
            allRevs.add(rev.replace("r", ""))
        if line not in revLogMatched:
            revLogMatched.add(line)
            sys.stderr.write(f"match rev: {line}\n")

    # NG: Run-Time Check Failure #3
    r = re.finditer(r"(\w*)(?<!Run-Time Check Failure )#(\d+)((?=[^0-9-&/=@_])|$)", line)
    for m in r:
        prefix = m.group(1)
        issue  = m.group(2)
        if prefix == "" or prefix == "SVN":
            allIssues.add(issue.replace("#", ""))
            if line not in issueLogMatched:
                issueLogMatched.add(line)
                sys.stderr.write(f"match issue: {line}\n")
        else:
            if line not in issueLogUnmatched:
                issueLogUnmatched.add(line)
                sys.stderr.write(f"ignore issue: {line}\n")

if allIssues:
    # print empty line for paragraph.
    print("")
    print("Issues:")
    for issue in sorted(list(allIssues), key=int):
        print(f"* https://osdn.net/projects/ttssh2/ticket/{issue}")

if allRevs:
    print("")
    print("Revisions:")
    showHashes(sorted(list(allRevs), key=int))
