name: Run
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.svg'

    branches:
      - main
      - 'feature/**'
      - 'research/**'
      - 'releases/**'
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'

    branches:
      - main
      - 'feature/**'
      - 'research/**'
      - 'releases/**'

  # Manual trigger
  workflow_dispatch:

  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 19:00 UTC:
    - cron:  '0 19 * * *'

env:
  svn-cache-version: v2
  svn-filter-cache-version: v3
  cache-version: v3
  retention-days: 14
  LANG: "ja_JP.UTF-8"
  svn-org: workdir/ttssh2.org
  svn-filtered: workdir/ttssh2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Tokyo"

      - name: Install svn-all-fast-export
        run: |-
          set -e
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            svn-all-fast-export

      - name: ja_JP.UTF-8
        run: |
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8

      - name: date
        run: |
            date

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/ )
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV

      - name: show revision
        id: show_revision
        run: |
          echo "${{env.revision}}"

      - name: create cache directories. (This is for the first time build.)
        run: |
          mkdir -p workdir
          mkdir -p ${{env.svn-org}}
          mkdir -p ${{env.svn-filtered}}

      # dependency
      # * Upstream svn repository
      #   * Revision                        : ${{env.revision}}
      - name: Get cached (id_cache-svn)
        id: cache-svn
        uses: actions/cache@v3
        with:
          path: ${{env.svn-org}}
          key: ${{env.svn-cache-version}}-ttssh2-r${{env.revision}}
          restore-keys: |
            ${{env.svn-cache-version}}-ttssh2-r10435
            ${{env.svn-cache-version}}-ttssh2-r10379

      - name: mirror (depends on id_cache-svn)
        run: |
          ./1.mirror-ttssh2.sh

      - name: archive SVN org
        working-directory: workdir
        run: |
          tar cfj ttssh2-org-svn.tar.bz2      ttssh2.org

      # dependency
      # * Upstream svn repository
      #   * Revision                        : ${{env.revision}}
      # * filtered svn repository
      #   * script to filter svn dump       : '2.filter-svndmp.sh'
      #   * script to create user map       : 'make-identity-map.py'
      #   * input data user map             : 'user-list.csv'
      - name: Get cached (id_cache-svn-filtered)
        id: cache-svn-filtered
        uses: actions/cache@v3
        with:
          path: ${{env.svn-filtered}}
          key: ${{env.svn-filter-cache-version}}-ttssh2-svn-filtered-r${{env.revision}}-${{ hashFiles('2.filter-svndmp.sh') }}

      - name: filter svn dump (cache-svn-filtered)
        if: ${{ steps.cache-svn-filtered.outputs.cache-hit != 'true' }}
        run: |
          ./2.filter-svndmp.sh

      - name: svn log
        run: |
          ./3.svnlog.sh

      - name: archive SVN
        working-directory: workdir
        run: |
          tar cfj ttssh2-svn.tar.bz2      ttssh2

      - name: artifacts SVN repository
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_number}}-${{github.run_id}}-SVN-repos
          path: |
            workdir/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: artifacts SVN log
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_number}}-${{github.run_id}}-SVN-log
          path: |
            workdir/**.log
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: migrate
        run: |
          ./4.migrate.sh

      - name: git repack
        run: |
          ./5.git-repack.sh

      - name: artifacts migration log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts-${{github.run_number}}-${{github.run_id}}-migration-log
          path: |
            workdir/gitdir/gitlog-ttssh2
            workdir/gitdir/log-ttssh2
            workdir/gitdir/log-migration.log
            workdir/gitdir/log-NotFound.log
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: extract filenames
        run: |
          ./6.extract-filenames.sh

      - name: artifacts filenames
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_number}}-${{github.run_id}}-filenames
          path: |
            workdir/file*.txt
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: archive GIT
        working-directory: workdir/gitdir-repack
        run: |
          tar cfj ttssh2-git.tar.bz2      ttssh2

      - name: artifacts GIT repository
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_number}}-${{github.run_id}}-GIT-repos
          path: |
            workdir/gitdir-repack/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}
