name: Run
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'

  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 5:00 and 19:00 UTC:
    - cron:  '0 5,19 * * *'

env:
  cache-version: v2
  retention-days: 2
  LANG: "ja_JP.UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install svn-all-fast-export
        run: |
            sudo apt install -y svn-all-fast-export

      - name: ja_JP.UTF-8
        run: |
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8

      - name: date
        run: |
            date

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/)
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV

      - name: show revision
        id: show_revision
        run: |
          echo "${{env.revision}}"

      - name: prepare cache directory (This is for the first time build.)
        run: |
          mkdir -p workdir/ttssh2.org
          ls workdir/ttssh2.org
          echo "key        = ${{env.cache-version}}-ttssh2-r${{env.revision}}"

      - name: Cache
        id: cache-svn
        uses: actions/cache@v3
        with:
          path: workdir/ttssh2.org
          key: ${{env.cache-version}}-ttssh2-r${{env.revision}}

      - name: mirror
        run: |
          echo "${{env.revision}}"
          echo "key        = ${{env.cache-version}}-ttssh2-r${{env.revision}}"
          echo "cache-hit  = ${{steps.cache-svn.outputs.cache-hit}}"
          ./1.mirror-ttssh2.sh

      - name: filter svn dump
        run: |
          ./2.filter-svndmp.sh

      - name: archive SVN
        working-directory: workdir
        run: |
          tar cfj ttssh2-svn.tar.bz2      ttssh2

      - name: artifacts SVN repository
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-SVN-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: migrate
        run: |
          ./migrate.sh

      - name: artifacts migration log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: migration-log-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/gitdir/gitlog-ttssh2
            workdir/gitdir/log-ttssh2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: archive GIT
        working-directory: workdir/gitdir
        run: |
          tar cfj ttssh2-git.tar.bz2      ttssh2

      - name: artifacts GIT repository
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-GIT-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/gitdir/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}
