name: Run
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'

env:
  cache-version: v2
  LANG: "ja_JP.UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ja_JP.UTF-8
        run: |
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8

      - name: date
        run: |
            date

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/)
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV

      - name: show revision
        id: show_revision
        run: |
          echo "${{ env.revision }}"

      - name: prepare cache directory (This is for the first time build.)
        run: |
          mkdir -p workdir/ttssh2.org
          ls workdir/ttssh2.org

      - name: Cache
        id: cache-svn
        uses: actions/cache@v3
        with:
          path: workdir/ttssh2.org
          key: ${{ env.cache-version }}-ttssh2

      - name: mirror
        run: |
          echo "${{ env.revision }}"
          echo "key        = ${{ env.cache-version }}-ttssh2"
          echo "cache-hit  = ${{steps.cache-svn.outputs.cache-hit}}"
          ./workdir/1.mirror-ttssh2.sh

      - name: filter svn dump
        run: |
          ./workdir/2.fiter-svndmp.sh

      - name: build docker image
        run: |
          ./docker-shell.sh build

      - name: migrate
        run: |
          ./docker-shell.sh migrate


      - name: archive
        working-directory: workdir
        run: |
          tar cfj ttssh2-svn.tar.bz2      ttssh2

      - name: archive
        working-directory: workdir/gitdir
        run: |
          tar cfj ttssh2-git.tar.bz2      ttssh2.git

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            workdir/**.tar.bz2
            workdir/gitdir/**.tar.bz2

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts log
          path: |
            workdir/gitdir/gitlog-ttssh2.git
            workdir/gitdir/log-ttssh2.git
