name: Run
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.svg'

    branches:
      - main
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'

    branches:
      - main
      - 'feature/**'
      - 'releases/**'

  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 5:00 and 19:00 UTC:
    - cron:  '0 5,19 * * *'

env:
  cache-version: v2
  retention-days: 2
  LANG: "ja_JP.UTF-8"
  svn-org: workdir/ttssh2.org
  svn-step2: workdir/ttssh2.step2
  svn-final: workdir/ttssh2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install svn-all-fast-export
        run: |
            sudo apt install -y svn-all-fast-export

      - name: ja_JP.UTF-8
        run: |
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8

      - name: date
        run: |
            date

      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the youngest revision
        id: get_revision
        run: |
          REVISION=$(svn info  --no-newline --show-item revision http://svn.osdn.net/svnroot/ttssh2/ )
          echo "revision=$REVISION" >> $GITHUB_ENV
          cat  $GITHUB_ENV

      - name: show revision
        id: show_revision
        run: |
          echo "${{env.revision}}"

      - name: create cache directories. (This is for the first time build.)
        run: |
          mkdir -p ${{env.svn-org}}
          mkdir -p ${{env.svn-step2}}
          mkdir -p ${{env.svn-final}}

      # dependency
      # * Upstream svn repository
      #   * Revision                        : ${{env.revision}}
      - name: Cache svn original
        id: cache-svn
        uses: actions/cache@v3
        with:
          path: ${{env.svn-org}}
          key: ${{env.cache-version}}-ttssh2-r${{env.revision}}
          restore-keys: |
            ${{env.cache-version}}-ttssh2-r10379

      - name: mirror
        run: |
          ./1.mirror-ttssh2.sh

      # dependency
      # * Upstream svn repository
      #   * Revision                        : ${{env.revision}}
      # * filtered svn repository
      #   * script to filter svn dump       : '2.filter-svndmp.sh'
      #   * script to create user map       : 'make-identity-map.py'
      #   * input data user map             : 'user-list.csv'
      - name: Cache svn filtered
        id: cache-svn-filtered
        uses: actions/cache@v3
        with:
          path: ${{env.svn-step2}}
          key: ${{env.cache-version}}-ttssh2-svn-filtered-r${{env.revision}}-${{ hashFiles('2.filter-svndmp.sh', 'make-identity-map.py', 'user-list.csv') }}

      - name: filter svn dump
        if: ${{ steps.cache-svn-filtered.outputs.cache-hit != 'true' }}
        run: |
          ./2.filter-svndmp.sh

      - name: svn log
        run: |
          ./3.svnlog.sh

      # dependency
      # * Upstream svn repository
      #   * Revision                        : ${{env.revision}}
      # * filtered svn repository
      #   * script to filter svn dump       : '2.filter-svndmp.sh'
      #   * script to create user map       : 'make-identity-map.py'
      #   * input data user map             : 'user-list.csv'
      # * mangled svn repository
      #   * shell script to mangle svn log  : '4.rewrite-svnlog.sh'
      #   * script to mangle svn log        : 'convert-svn-log.py'
      - name: Cache svn final
        id: cache-svn-final
        uses: actions/cache@v3
        with:
          path: ${{env.svn-final}}
          key: ${{env.cache-version}}-ttssh2-svn-final-r${{env.revision}}-${{ hashFiles('2.filter-svndmp.sh', 'make-identity-map.py', 'user-list.csv', '4.rewrite-svnlog.sh', 'convert-svn-log.py') }}

      - name: svn log rewrite
        if: ${{ steps.cache-svn-final.outputs.cache-hit != 'true' }}
        run: |
          ./4.rewrite-svnlog.sh

      - name: archive SVN
        if: ${{ steps.cache-svn-final.outputs.cache-hit != 'true' }}
        working-directory: workdir
        run: |
          tar cfj ttssh2-svn.tar.bz2      ttssh2

      - name: artifacts SVN repository
        uses: actions/upload-artifact@v3
        if: ${{ steps.cache-svn-final.outputs.cache-hit != 'true' }}
        with:
          name: artifacts-SVN-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: artifacts SVN log
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-SVN-log-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/**.log
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: migrate
        run: |
          ./migrate.sh

      - name: artifacts migration log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: migration-log-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/gitdir/gitlog-ttssh2
            workdir/gitdir/log-ttssh2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: extract filenames
        run: |
          ./extract-filenames.sh

      - name: artifacts filenames
        uses: actions/upload-artifact@v3
        with:
          name: filenames-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/file*.txt
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}

      - name: archive GIT
        working-directory: workdir/gitdir
        run: |
          tar cfj ttssh2-git.tar.bz2      ttssh2

      - name: artifacts GIT repository
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-GIT-build-${{github.run_number}}-${{github.run_id}}
          path: |
            workdir/gitdir/**.tar.bz2
          # See https://github.com/actions/upload-artifact#retention-period
          retention-days: ${{env.retention-days}}
